### ISSUE TITLE
Reproducing results for one shot case

### ISSUE THREAD

**Issue by hila-chefer** [KaiyangZhou/CoOp#11]
Hi,

thanks for your great work!
You state in your paper that the one shot experiments are trained for 50 epochs, but after using your code, it looks like the results you report for one shot are consistent with training for 200 epochs. When training with 50 epochs, I obtain results that are much better than those reported in the paper.

Any idea on what causes this?

Thanks!

**Comment by KaiyangZhou** [comment]
The results in the paper are sort of outdated since some changes have been made to the code. See this https://github.com/KaiyangZhou/CoOp#updates. The gaps between the compared methods remain the same, however.
