### ISSUE TITLE
Why do token prefixes have to be a buffer type

### ISSUE THREAD

**Issue by nbl97** [KaiyangZhou/CoOp#16]
If the token prefixes and suffix are just the slice of the embedding, for example, replacing `self.register_buffer("token_prefix", embedding[:, :1, :])` with `self.token_prefix=embedding[:, :1, :])` in [this line](https://github.com/KaiyangZhou/CoOp/blob/main/trainers/coop.py#L109), we will not have to ignore those when loading. Therefore, why do token prefixes have to be a buffer type? Thanks a lot!

**Comment by KaiyangZhou** [comment]
That makes sense!

But I sort of remember that we made this design due to some reasons which I forgot (maybe you're right, it's not necessary)

**Comment by samuelyu2002** [comment]
I think making it a buffer is necessary if you wrap the model with DataParallel. If it isn't a buffer then it won't be sent to each GPU.

**Comment by KaiyangZhou** [comment]
@samuelyu2002 ah, yes!

**Comment by nbl97** [comment]
@samuelyu2002 @KaiyangZhou I got it! Many thanks!

**Comment by littlexinyi** [comment]
If the token_suffix is a buffer, do we also use it as the global embedding when after the CLIP Text Transformer encoder? What I am concerned about is that the buffer token_suffix will not be updated when transformer learning.
