### ISSUE TITLE
About the configuration of "classnames"

### ISSUE THREAD

**Issue by xujinglin** [KaiyangZhou/CoOp#18]
Thanks for your contributions!

I have a question about "classnames = self.dm.dataset.classnames" (the line 224 of "CoOp.build_model" in coop.py).
What is the value of "classnames"? I checked the configuration files and didn't find out.

**Comment by KaiyangZhou** [comment]
Classnames are defined in datasets code, e.g., https://github.com/KaiyangZhou/CoOp/blob/main/datasets/oxford_pets.py#L51

You may want to have a look at the definition of the basic datum object at here https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/datasets/base_dataset.py#L12

**Comment by xujinglin** [comment]
> Classnames are defined in datasets code, e.g., https://github.com/KaiyangZhou/CoOp/blob/main/datasets/oxford_pets.py#L51
> 
> You may want to have a look at the definition of the basic datum object at here https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/datasets/base_dataset.py#L12

Thanks~~~
