### ISSUE TITLE
Inferencing on single image

### ISSUE THREAD

**Issue by ChandanVerma** [KaiyangZhou/CoOp#19]
I have been successful in developing the train and test pipeline for my custom dataset. Can you help me out for making inference on a single image. I am using the trainer.model_inference(image) function. Is there a particular format this image needs to be in ? I am using PIL to read the image. 

Error:
/ContextOptimization/CoOp/trainers/coop.py", line 196, in forward
    image_features = self.image_encoder(image.type(self.dtype))
  File "/home/chandan/anaconda3/envs/coop/lib/python3.8/site-packages/PIL/Image.py", line 519, in __getattr__
    raise AttributeError(name)
AttributeError: type

Main function used:

def main(args):
    cfg = setup_cfg(args)
    if cfg.SEED >= 0:
        print("Setting fixed seed: {}".format(cfg.SEED))
        set_random_seed(cfg.SEED)
    setup_logger(cfg.OUTPUT_DIR)

    if torch.cuda.is_available() and cfg.USE_CUDA:
        torch.backends.cudnn.benchmark = True

    print_args(args, cfg)
    print("Collecting env info ...")
    print("** System info **\n{}\n".format(collect_env_info()))

    trainer = build_trainer(cfg)

    trainer.load_model(args.model_dir, epoch=args.load_epoch)
    image = Image.open('/ContextOptimization/CoOp/data/0cd2ed50.png')
    result = trainer.model_inference(image)
    print(result)
    return result

I am looking for the predicted class and predicted probabilities as output.

Any direction would be appreciative.

Thanks

**Comment by ChandanVerma** [comment]
Resolved. This is what i used:
_, preprocess = clip.load("ViT-B/16", device=device)
trainer = build_trainer(cfg)
trainer.load_model(args.model_dir, epoch=args.load_epoch)
image = cv2.imread('0cd2ed50.png')
image_torch = (preprocess(Image.fromarray(image)).unsqueeze(0).to(device))
result = trainer.model_inference(image_torch)

The preprocess is the same as we use in CLIP repo:

**Comment by StephanPan** [comment]
how to get the prompt embedding for image-text retrieval?
