### ISSUE TITLE
ModuleNotFoundError: No module named 'trainers.ours

### ISSUE THREAD

**Issue by SimonsFPV** [KaiyangZhou/CoOp#2]
Hello, 
when I try to run one of your example bash commands, I somehow can't figure out how to get rid of this error. 

`(dassl) user@MBP scripts % bash main.sh caltech101 rn50_ep50 middle 16 1 True
Run this job and save the output to output/caltech101/CoOp/rn50_ep50_1shots/nctx16_cscTrue_ctpmiddle/seed1
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    import trainers.zsclip
  File "/Users/user/Projects/CoOp/CoOp/trainers/zsclip.py", line 10, in <module>
    from .ours import load_clip_to_cpu
ModuleNotFoundError: No module named 'trainers.ours'`

**Comment by KaiyangZhou** [comment]
Good spot.

I've fixed the error. Please pull the latest commit.
