### ISSUE TITLE
Different random seeds lead to highly variable results.

### ISSUE THREAD

**Issue by guozix** [KaiyangZhou/CoOp#24]
First of all, thank you for open sourcing such an easy to use code :)
I reproduced your reported results in **CoOp** on two datasets, **DTD** and **Flower101**. I ran the code with three random seeds,1,2 and 3 for both datasets, as your default setting in  ./scripts/main.sh.
The performance of model on DTD is as well as the result in paper (acc: 63.46) when trained with seed=3, but the results of seed 1 and 2 are poor (acc: ~15).
As for Flower101, the result of seed 2 and 3 are ~94, but seed 1's result is 44.50

I wonder if this is a normal situation for this few shot training setting? Thanks for any suggestion :)

**Comment by KaiyangZhou** [comment]
can you be more specific like how many shots did you use? which backbone? etc.

**Comment by guozix** [comment]
> can you be more specific like how many shots did you use? which backbone? etc.

Thanks for your reply.
I use:
- backbone: resnet50
- class token position at the end
- 16 context tokens
- 16 shots
- class-specific context is set as False
for both dtd and oxford_flowers.
The results are：
dtd:
1. seed1: accuracy: 12.00%
2. seed2: accuracy: 15.19%
3. seed3: accuracy: 63.42%
oxford_flowers:
1. seed1: accuracy: 44.50%
2. seed2: accuracy: 93.87%
3. seed3: accuracy: 94.97%

**Comment by KaiyangZhou** [comment]
here are my results for seed-1/2/3
- dtd: 62.53, 64.07, 64.13
- oxford-flowers: 94.68, 94.44, 94.40

it's rare to see the large variances in the results using 16 shots (even for 1 shot, the variances of dtd and oxford-flowers in my case are 1.23 and 1.16, pretty small)

**Comment by guozix** [comment]
> here are my results for seed-1/2/3
> 
> * dtd: 62.53, 64.07, 64.13
> * oxford-flowers: 94.68, 94.44, 94.40
> 
> it's rare to see such large variances (in your case) when using 16 shots
> 
> even for 1 shot, the variances of dtd and oxford-flowers in my case are 1.23 and 1.16, which are pretty small

Thanks. I'll try again with different environment and different backbone.
