### ISSUE TITLE
Much better CoOp performance

### ISSUE THREAD

**Issue by fanq15** [KaiyangZhou/CoOp#27]
Thanks for your great work!
I tried to use your code to reproduce some results of CoOp reported in your CoCoOp paper.
I tried this model on the `dtd` dataset with:
`bash main.sh dtd vit_b16_ep50 end 4 16 False`.
Which is exactly same as the setting in the paper.
I got a much higher performance: `accuracy: 67.38% +- 0.51%`.
But the paper report CoOp performance as `54.24`.

**Comment by KaiyangZhou** [comment]
I guess you misused the scripts. There are differences in the implementation of the settings used in CoOp and CoCoOp. Please see the latest scripts where I've put some comments on how to run CoOp under CoCoOp's settings. Thanks
